
//UI 
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_NUTRIENT_DETAILS = "TOGGLE_NUTRIENT_DETAILS";
export const TOGGLE_DAILY_DETAILS = "TOGGLE_DAILY_DETAILS";

//API
export const MAIN_SEARCH_TEXT_CHANGE = "MAIN_SEARCH_TEXT_CHANGE";