
//UI 
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_NUTRIENT_DETAILS = "TOGGLE_NUTRIENT_DETAILS";
export const TOGGLE_DAILY_DETAILS = "TOGGLE_DAILY_DETAILS";

//API
export const MAIN_SEARCH_TEXT_CHANGE = "MAIN_SEARCH_TEXT_CHANGE";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const ORIGINAL_HEALTH_STATE = "ORIGINAL_HEALTH_STATE";
export const UPDATE_HEALTH_STATE = "UPDATE_HEALTH_STATE";
export const HEALTH_ITEM_CHANGE = "HEALTH_ITEM_CHANGE";